#+STARTUP: hidestars showall
* <2011-05-10 Tue>
** Scaling and zooming
file:scale-and-offset.svg

  - Since QImage does not support scaling and cropping in one atomic command this must be done in the following two commands:
    - scale the s_copy_w area by the scale factor
    - copy and crop while ignoring the red areas.
* <2011-05-16 Mon>
** Done
   - Fixed repaint bug that stopped scrolling from working.
   - Added mouse scroll event and keyboards event.
   - Added several more zoom functions from gtkimageviewer.
** Bugs
   - [ ] There is an offset bug visible at high zoom ratios. Probably due to an error in the calculation of offsets in paintEvent.
** Todo
   - [X] Figure out how to support scroll bars.
   - [ ] Check if empty canvas without underlying image works.
   - [ ] Start working on overlay.

* <2011-05-20 Fri>
** Scrolling
   - Checkout out the qt sources and investigated how ~QTextEdit~ does it. What I found is that ~QTextEdit~ inherits from ~QAbstractScrollArea~ and it is responsible on its own for showing the scrollbars. This actually makes the interaction with the scrollbars much easier than through the gtk abstraction.
* <2011-05-22 Sun>
  * Todo
    - [X] Changed the parent of ~QvivImageViewer~ from ~Qwidget~ to ~QAbstractScrollArea~.
    - [X] Connect view changed to scrollbar changes.
    - [X] Connect scrollbar changes to view changes.
    - [ ] Support vertical flip.
    - [ ] Support horizontal flip.
* <2011-05-23 Mon>
** Todo
   - [X] Created example in QvivImage of how to draw in the imageAnnotate event.
* <2011-05-31 Tue>
** Signal woes 
   - [X] Why can't ~test-qviv-image-viewer.cc~ connect to the signal ~mouseMoveEvent(QMouseEvent*)~. Worked around it by introducing a signal of my own ~qvivMouseMoveEvent()~ that just relays this signal. *Answer*: There is a difference between events that may be overloaded and signals that may be received. The ~mouseMoveEvent()~ is an event, but since my test program is not inheriting from it, it can not catch the signal. The solution is to create a signal in my widget and translate the event into a signal.
   - Mouse motion event with relay works.
   - [X] Create a tooltip.
   - [X] Make tooltip change position with mouse motion.
   - [X] Change tooltip contents with mouse motion.
   - [X] How to make the size of the tooltip window fit the text? How do you get the natural size of a text label. Test adjustSize() that I found on the net
   - [X] Change the label background to Yellow. 
   - [X] Make label popdown on widget focus leave and show in motion handle.
   - [ ] Implement ~CanvasToImg()~ and ~ImgToCanvas()~
   - [ ] Data structure for giv data.
   - [ ] Start implemenatino of =QvivWidget= based on the reference implementation in ~test-qviv-image-viewer~. 
* <2011-06-06 Mon>
** Notes
   - [ ] Something is wrong with the position as seen by an example program drawing a circle at (0,0). Make sure it is always drawn correctly! What is the difference between Qviv and Giv?
   - [X] Start of QvivWidget.
     - [X] Override signals.
     - [X] Balloon support.
   - [X] Implement ~CanvasToImg()~ and ~ImgToCanvas()~
   - [ ] Changed drawing of circles to use (x0,y0,size_x,size_y) coordinates.
** Drawing sub-pixel position
   - Annotation and motion are ok.
   - [ ] Pixmap drawing is not accurate.
   - [ ] Spurious annotations drawn. Why?
   - [ ] Investigated image and calculations for sub pixel copying. Looks ok. So what is wrong?
   - [X] If widget is constraint to two powers, it works.
   - [ ] Check arithmetics rounding errors.
* <2011-06-10 Fri>
** Pixel scaling problem
   - It turns out that scaling is not accurate for large scales when using ~Qt::FastTransformation~ for 0th order interpolation. The resulting image has the correct size, but the pixel boundaries appear to be powers of 2. There does not seem to be any way to work around this problem except for rewriting the scaling function myself for large scaling factors!
   - [X] Dragging doesn't work in ~test-qviv-image-viewer~.
   - [X] Wrote replacement for QImage::scaled().
* <2011-06-12 Sun>
** Data set
   - [X] Started implementing a data set structure.
   - [X] Changed test program to use this new structure.
** Balloon
   - [X] Got problem with motion of balloon under X11. Solved by using ~X11BypassWindowManagerHint~ flag.
   - [ ] Test balloon under Windows.
   
   
