#+STARTUP: hidestars showall
* <2011-05-10 Tue>
** Scaling and zooming
file:scale-and-offset.svg

  - Since QImage does not support scaling and cropping in one atomic command this must be done in the following two commands:
    - scale the s_copy_w area by the scale factor
    - copy and crop while ignoring the red areas.
* <2011-05-16 Mon>
** Done
   - Fixed repaint bug that stopped scrolling from working.
   - Added mouse scroll event and keyboards event.
   - Added several more zoom functions from gtkimageviewer.
** Bugs
   - [ ] There is an offset bug visible at high zoom ratios. Probably due to an error in the calculation of offsets in paintEvent.
** Todo
   - [X] Figure out how to support scroll bars.
   - [ ] Check if empty canvas without underlying image works.
   - [ ] Start working on overlay.

* <2011-05-20 Fri>
** Scrolling
   - Checkout out the qt sources and investigated how ~QTextEdit~ does it. What I found is that ~QTextEdit~ inherits from ~QAbstractScrollArea~ and it is responsible on its own for showing the scrollbars. This actually makes the interaction with the scrollbars much easier than through the gtk abstraction.
* <2011-05-22 Sun>
  * Todo
    - [X] Changed the parent of ~QvivImageViewer~ from ~Qwidget~ to ~QAbstractScrollArea~.
    - [X] Connect view changed to scrollbar changes.
    - [X] Connect scrollbar changes to view changes.
    - [ ] Support vertical flip.
    - [ ] Support horizontal flip.
* <2011-05-23 Mon>
** Todo
   - [X] Created example in QvivImage of how to draw in the imageAnnotate event.
