env = Environment(tools=['default','qt4'])

env.EnableQt4Modules(['QtGui'])
env.Program('testOverlay',
            ['testOverlay.cc',
             'overlay.cc'])


env.Program('testLasso',
            ['testLasso.cc',
             'qvivLasso.cc',
             'overlay.cc',
             ])
